[libraries]
mavenPublishPlugin = "com.vanniktech:gradle-maven-publish-plugin:0.35.0"

rxjava3 = "io.reactivex.rxjava3:rxjava:3.1.12"

junit = "junit:junit:4.13.2"
mockito = "org.mockito:mockito-core:5.20.0"
